# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.vault.name }}
  labels:
    app: {{ .Values.global.vault.name }}
data:
  vault_token: {{ .Values.global.vault.vaultToken | b64enc | quote }}
type: Opaque